export const watchedTest = [
  {
    adult: false,
    backdrop_path: '/1mY2vJCGQW2IUgGK6yNc852A4tR.jpg',
    belongs_to_collection: {
      id: 529,
      name: 'Wallace & Gromit Collection',
      poster_path: 'https://image.tmdb.org/t/p/w780/rD3IjijBs1pC8XDE9q9FSKsjjk.jpg',
      backdrop_path: '/zFjNVIdhOh8KlJESKXf6.jpg',
    },
    budget: 0,
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 16, name: 'Animation' },
      { id: 35, name: 'Comedy' },
      { id: 878, name: 'Science Fiction' },
      { id: 10751, name: 'Family' },
    ],
    homepage: 'https://www.wallaceandgromit.com/films/a-grand-day-out',
    id: 530,
    imdb_id: 'tt0104361',
    original_language: 'en',
    original_title: 'A Grand Day Out',
    overview:
      'Wallace and Gromit have run out of cheese and this provides an excellent excuse for the animated duo to take their holiday on the moon, where, as everyone knows, there is ample cheese. The moon is inhabited by a mechanical caretaker, who is not too happy about the two visitors from earth that nibble on the moon.',
    popularity: 8.518,
    poster_path: 'https://image.tmdb.org/t/p/w780/og1s6iwv73WMShgNzg0WTtmrKXy.jpg',
    production_companies: [
      {
        id: 297,
        logo_path: '/ykJbf1z5qIreJrHWfnh1ev1alkD.png',
        name: 'Aardman Animations',
        origin_country: 'GB',
      },
      { id: 17700, logo_path: null, name: 'NFTS', origin_country: 'GB' },
    ],
    production_countries: [{ iso_3166_1: 'GB', name: 'United Kingdom' }],
    release_date: '1990-05-18',
    revenue: 0,
    runtime: 23,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en', name: 'English' }],
    status: 'Released',
    tagline: '',
    title: 'A Grand Day Out',
    video: false,
    vote_average: 7.5,
    vote_count: 560,
  },
  {
    adult: false,
    backdrop_path: '/2oum8FkgH1AiDWhmhEw8nbtoHdJ.jpg',
    belongs_to_collection: null,
    budget: 14390509,
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 18, name: 'Drama' },
      { id: 10749, name: 'Romance' },
    ],
    homepage: '',
    id: 175,
    imdb_id: 'tt0095250',
    original_language: 'fr',
    original_title: 'Le Grand Bleu',
    overview:
      'Two men answer the call of the ocean in this romantic fantasy-adventure.  Jacques and Enzo are a pair of friends who have been close since childhood, and who share a passion for the dangerous sport of free diving. Professional diver Jacques opted to follow in the footsteps of his father, who died at sea when Jacques was a boy; to the bewilderment of scientists, Jacques harbors a remarkable ability to adjust his heart rate and breathing pattern in the water, so that his vital signs more closely resemble that of dolphins than men.  As Enzo persuades a reluctant Jacques to compete against him in a free diving contest -- determining who can dive deeper and longer without scuba gear -- Jacques meets Johana, a beautiful insurance investigator from America, and he finds that he must choose between his love for her and his love of the sea.',
    popularity: 11.84,
    poster_path: 'https://image.tmdb.org/t/p/w780/vbi56h6a1BGjnhq2RnUrcQZs2aV.jpg',
    production_companies: [
      {
        id: 9,
        logo_path: '/nda3dTUYdDrJ6rZqBpYvY865aDv.png',
        name: 'Gaumont',
        origin_country: 'FR',
      },
    ],
    production_countries: [
      { iso_3166_1: 'FR', name: 'France' },
      { iso_3166_1: 'IT', name: 'Italy' },
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '1988-05-10',
    revenue: 0,
    runtime: 168,
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
      { english_name: 'French', iso_639_1: 'fr', name: 'Français' },
      { english_name: 'Italian', iso_639_1: 'it', name: 'Italiano' },
    ],
    status: 'Released',
    tagline: 'Danger...Like Passion...Runs Deep',
    title: 'The Big Blue',
    video: false,
    vote_average: 7.5,
    vote_count: 1030,
  },
  {
    adult: false,
    backdrop_path: '/fq3wyOs1RHyz2yfzsb4sck7aWRG.jpg',
    belongs_to_collection: {
      id: 264,
      name: 'Back to the Future Collection',
      poster_path: 'https://image.tmdb.org/t/p/w780/78z0WMBzBWOnCsXWulihPJKCToL.jpg',
      backdrop_path: '/AqQotqj7XOI6GjB28nhMMa8YzOT.jpg',
    },
    budget: 19000000,
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 35, name: 'Comedy' },
      { id: 878, name: 'Science Fiction' },
      { id: 10751, name: 'Family' },
    ],
    homepage: 'http://www.backtothefuture.com/movies/backtothefuture1',
    id: 105,
    imdb_id: 'tt0088763',
    original_language: 'en',
    original_title: 'Back to the Future',
    overview:
      "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
    popularity: 33.224,
    poster_path: 'https://image.tmdb.org/t/p/w780/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
    production_companies: [
      {
        id: 33,
        logo_path: '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
        name: 'Universal Pictures',
        origin_country: 'US',
      },
      {
        id: 56,
        logo_path: '/cEaxANEisCqeEoRvODv2dO1I0iI.png',
        name: 'Amblin Entertainment',
        origin_country: 'US',
      },
    ],
    production_countries: [{ iso_3166_1: 'US', name: 'United States of America' }],
    release_date: '1985-07-03',
    revenue: 381109762,
    runtime: 116,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en', name: 'English' }],
    status: 'Released',
    tagline: "He's the only kid ever to get into trouble before he was born.",
    title: 'Back to the Future',
    video: false,
    vote_average: 8.3,
    vote_count: 15098,
  },
];

export const queueTest = [
  {
    adult: false,
    backdrop_path: '/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
    belongs_to_collection: null,
    budget: 165000000,
    genres: [
      { id: 12, name: 'Adventure' },
      { id: 18, name: 'Drama' },
      { id: 878, name: 'Science Fiction' },
    ],
    homepage: 'http://www.interstellarmovie.net/',
    id: 157336,
    imdb_id: 'tt0816692',
    original_language: 'en',
    original_title: 'Interstellar',
    overview:
      'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    popularity: 85.103,
    poster_path: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    production_companies: [
      {
        id: 923,
        logo_path: '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png',
        name: 'Legendary Pictures',
        origin_country: 'US',
      },
      {
        id: 9996,
        logo_path: '/3tvBqYsBhxWeHlu62SIJ1el93O7.png',
        name: 'Syncopy',
        origin_country: 'GB',
      },
      { id: 13769, logo_path: null, name: 'Lynda Obst Productions', origin_country: '' },
    ],
    production_countries: [
      { iso_3166_1: 'GB', name: 'United Kingdom' },
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '2014-11-05',
    revenue: 675120017,
    runtime: 169,
    spoken_languages: [{ english_name: 'English', iso_639_1: 'en', name: 'English' }],
    status: 'Released',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    title: 'Interstellar',
    video: false,
    vote_average: 8.3,
    vote_count: 25994,
  },
];

export const filmToCheckOne = {
  adult: false,
  backdrop_path: '/ELsTifJ2lu4vsMhoHeZ5EnncHw.jpg',
  belongs_to_collection: null,
  budget: 70000000,
  genres: [
    { id: 35, name: 'Comedy' },
    { id: 14, name: 'Fantasy' },
    { id: 878, name: 'Science Fiction' },
  ],
  homepage: 'https://www.warnerbros.com/movies/mars-attacks/',
  id: 75,
  imdb_id: 'tt0116996',
  original_language: 'en',
  original_title: 'Mars Attacks!',
  overview:
    "'We come in peace' is not what those green men from Mars mean when they invade our planet, armed with irresistible weapons and a cruel sense of humor.  This star studded cast must play victim to the alien’s fun and games in this comedy homage to science fiction films of the '50s and '60s.",
  popularity: 14.163,
  poster_path: '/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg',
  production_companies: [
    { id: 8601, logo_path: null, name: 'Tim Burton Productions', origin_country: '' },
    {
      id: 174,
      logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
      name: 'Warner Bros. Pictures',
      origin_country: 'US',
    },
  ],
  production_countries: [{ iso_3166_1: 'US', name: 'United States of America' }],
  release_date: '1996-12-12',
  revenue: 101371017,
  runtime: 106,
  spoken_languages: [
    { english_name: 'English', iso_639_1: 'en', name: 'English' },
    { english_name: 'French', iso_639_1: 'fr', name: 'Français' },
  ],
  status: 'Released',
  tagline: "Nice planet. We'll take it!",
  title: 'Mars Attacks!',
  video: false,
  vote_average: 6.3,
  vote_count: 4044,
};

export const filmToCheckTwo = {
  adult: false,
  backdrop_path: '/guhVuJAqSEMrUgKMB04y0SXJr8Q.jpg',
  belongs_to_collection: null,
  budget: 375000,
  genres: [
    { id: 9648, name: 'Mystery' },
    { id: 80, name: 'Crime' },
    { id: 53, name: 'Thriller' },
  ],
  homepage: '',
  id: 963,
  imdb_id: 'tt0033870',
  original_language: 'en',
  original_title: 'The Maltese Falcon',
  overview:
    'A private detective takes on a case that involves him with three eccentric criminals, a beautiful liar, and their quest for a priceless statuette.',
  popularity: 9.555,
  poster_path: '/wcGLnRsuKyCYg3WLXQqIuB0lsJB.jpg',
  production_companies: [
    {
      id: 174,
      logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
      name: 'Warner Bros. Pictures',
      origin_country: 'US',
    },
  ],
  production_countries: [{ iso_3166_1: 'US', name: 'United States of America' }],
  release_date: '1941-10-18',
  revenue: 1772000,
  runtime: 100,
  spoken_languages: [{ english_name: 'English', iso_639_1: 'en', name: 'English' }],
  status: 'Released',
  tagline: 'A story as EXPLOSIVE as his BLAZING automatics!',
  title: 'The Maltese Falcon',
  video: false,
  vote_average: 7.8,
  vote_count: 1094,
};
